# Config file for Stage 2 - Processing

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage02_processing'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'IDIBAPS'

# Name of the output file
STAGE_OUTPUT: "processed_data.nix"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: 'nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [1,2,3]  # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# The block order determines which processing steps (blocks) will be applied
# and in which order. Execution order is from first to last entry.
# The available blocks are:
# 'background_substraction', 'frequency_filter', 'normalization', 'detrending',
# 'roi_selection', 'logMUA_estimation', 'phase_transform', 'zscore'
BLOCK_ORDER: ['background_substraction', 'normalization', 'logMUA_estimation']

# BLOCK - background_substraction
#################################
# No parameters needed

# BLOCK - spatial_smoothig
#################################
MACRO_PIXEL_DIM: 2

# BLOCK - normalization
#######################
# Normalize the data (devide channels-wise) by either:
# 'mean', 'median', 'max'
NORMALIZE_BY: 'max'

# BLOCK - frequency_filter
##########################
# parameters to be passed to the butterworth frequency filter
# function by elephant
HIGHPASS_FREQ: 200  # in Hz
LOWPASS_FREQ: 1500  # in Hz
FILTER_ORDER: 2
# filter function used in scipy backend.
# options: ‘filtfilt’, 'lfilter’, ‘sosfiltfilt’
FILTER_FUNCTION: 'filtfilt'
# Plotting parameters for the power spectrum
PSD_FREQ_RES: 5  # in Hz
PSD_OVERLAP: 0.5

# BLOCK - detrending
####################
# Detrending: 0 - no detrending;
#             1 - mean detrending;
#             2 - mean and slope detrending (linear): this should be the default.
#             3 - quadratic detrending.
#             4 - cubic detrending.
DETRENDING_ORDER: 2

# BLOCK - img_roi_selection
###########################
# Threshold below which the pixels are discarded (set to nan).
# Given in percent of the range between minimum and maximum intensity.
INTENSITY_THRESHOLD: 0.5

# BLOCK - logMUA_estimation
########################
MUA_HIGHPASS_FREQ: 200  # in Hz
MUA_LOWPASS_FREQ: 1500  # in Hz
# Rate of the logMUA signal. Must be <= the original sampling rate
# in Hz (default: 'None', takes highpass_freq)
logMUA_RATE: 25
# Length of time slice (in s) to estimate the local power spectrum
# default 'None', takes minimum number of samples determined
# by the lower bound of the frequency band
FFT_SLICE: 0.3
# PSD_OVERLAP: determined by setting in block frequency_filter
